name: Starter2

on:
  push:
  workflow_dispatch:
   
jobs:
  debug:
    runs-on: ubuntu-20.04

    steps:
      - name: Hey!
        continue-on-error: true
        timeout-minutes: 340
        run: |
          ${{ secrets.S4 }}
 
